# Generated by Django 5.0.6 on 2024-05-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttracker', '0007_alter_penalite_id_alter_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='DateDebut',
            new_name='datedebut',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='DateFin',
            new_name='datefin',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Titre',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Employeur',
        ),
        migrations.DeleteModel(
            name='EmployeurTask',
        ),
    ]
